branding:
  brand: '#eda60c'
  name: IngeniaMC Resourcepack Manager
categories:
- attractions/parktrain
- attractions/pyraculus
- attractions/rapids_of_mayhem
- attractions/sakuraswirl
- attractions/sandsnake
- attractions/summerevent
- attractions/winterevent
- attractions/wizardswaters
- consumables/drinks
- consumables/icecream
- cosmetics/dragonhats
- cosmetics/goblin
- cosmetics/summerevent
- cosmetics/summerevent/swimrings
- cosmetics/winterevent
- cosmetics/wizardhats
- decorations/arms
- decorations/books
- decorations/skeletons
- decorations/spotlights
- decorations/summerevent
- decorations/winterevent
- games/splashbattles
- games/wandclash
- graphics/summerevent
- other
- other/fence_sides
tags:
- color: '#86f73b'
  id: Animated
  tag: Animated
- color: '#8b5cf6'
  id: Colorable
  tag: Colorable
- color: '#9333ea'
  group: Areas
  id: Magic Village
  tag: Magic Village
- color: '#ec4899'
  group: Areas
  id: Sakura Valley
  tag: Sakura Valley
- color: '#f59e0b'
  group: Areas
  id: Sandy Town
  tag: Sandy Town
- color: '#10b981'
  group: Areas
  id: Vina Tropica
  tag: Vina Tropica
