branding:
  brand: oklch(0.58 0.256 293.597)
  name: IngeniaMC Resourcepack Manager
categories:
- test/test
- test2
tags:
- color: '#86f73b'
  group: null
  id: Animated
  tag: Animated
- color: '#8b5cf6'
  id: Colorable
  tag: Colorable
- color: '#9333ea'
  group: Areas
  id: Magic Village
  tag: Magic Village
- color: '#ec4899'
  group: Areas
  id: Sakura Valley
  tag: Sakura Valley
- color: '#f59e0b'
  group: Areas
  id: Sandy Town
  tag: Sandy Town
- color: '#10b981'
  group: Areas
  id: Vina Tropica
  tag: Vina Tropica
